language: java

matrix:
  include:
    - dist: trusty
      jdk: oraclejdk8
    - dist: xenial
      jdk: openjdk11

install: true

script:
  - |
    if [[ $TRAVIS_REPO_SLUG == "pinterest/ktlint" && $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      # Gradle
      ./gradlew clean publishMavenPublicationToMavenCentralRepository --no-daemon --no-parallel
      # Publishing kotlin dev snapshots if no git tag is present
      if [[ -z $TRAVIS_TAG ]]; then
        ./gradlew -PkotlinDev clean publishMavenPublicationToMavenCentralRepository --no-daemon --no-parallel
      fi
    else
      # Gradle with release Kotlin version
      ./gradlew clean build ktlint
      # Gradle with Kotlin dev version
      ./gradlew -PkotlinDev clean build ktlint
    fi

before_cache:
  - find $HOME/.gradle -name "*.lock" -type f -delete
  - find $HOME/.gradle -name "gc.properties" -type f -delete

# See https://docs.gradle.org/6.6/userguide/dependency_resolution.html#sub:cache_copy
cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/

env:
  global:
  - secure: sk+fF6EPGXCy85gm8cdKM0JXy3pMKRZSRaAE/gE+OWir9BjUj1clG3KZw5P/xPudiSMnNIRfluqxkLRCPWpawh/6Ixvs3falZAC9JVBu6OyHSjTXDp3zIr4Mv3NNMEefr775iRPzuf6iBUTTP2bZQ2P62CE3HOd83lB8Jm1QcDE7LIscMn96DGZt8BDi88fEjfSDCMcw87w+5zOM5prUoOlPp9dyxnskw9ncwmFLLrsJJJmcC0bvrTiE6Z1CduwNDOwYDDRgsEa6k2EEpBDrRSStDcXoF8zFTm79C5B81lkH2s+kylpp7XjOQPWQAs4+n/tQ0TIlvUG7YMyrtf/NVK+7oClQtVKAeWOD1sl+Z1Qs8h3+pk9xrTWFRgMYMSyjAbHAyaf7x+3Lv/uDs8yKdLc0QHa5kb6khJJ6M9wdQX6NDXopeuPIkacmHtknRi1BhUBzHCbiJDhxsQ08suaqjNtxVZ3ECh3GTLvnbTof3SN9IlUOu9SdS5iIGRGERxIY9YdNHHuT2zf95YNAkjS4zJqZG/q9rBxi5/YWgiBeSCARtqrEJ9aMMg3nvBFqsZs6AHB1KaAH8N15Z1n1EqzISn1/Mk5B17SG6+FSNswYomKP54HxeILE35iXOIRGcNyeE5GrNKgoofFhtRVJYUuIZu26ZY+hG39WwdGfDa8QBPE=
  - secure: A5FWMVZ7AY18WGMJ1JgUseELHKGPuk1V1ybsiS+ptOSZN5UyH4dNX9H2Yzv3yuYG0KW5SKhVivJHyrexHRX5qKacdwYlw2TWqmzw9MoegjmxIwMjGSOlSLE5x65etoKac0zUFHw4UNdto4lt7jTUFVOzwt7Oq9bWfox5lXBIhYfBWhNoBCZJPZeyVpY8uyk40xeIyJDFMU1l6IhpjxETf+/LeWT8jfkqcUOlPayV++wUFd+6k73h2t+dmqPcX2nKpZ6DHbPx7xS7IJgpcAaVWTyAyzzOoHzu0RSnnd0zrnjiBx2OMZ2aPPGNd1eF9sxqKguEFR9UAwtDB0CqY2VFY9pcUCuWSD5Zrckk0wy3IS/ZRd89x3p+/DW1Kr9Cb3pwZDwRjPmia1J584Ki+MBDkQL4BfAjWtnbHrp7shCBhRg813ZHeGQQxaC4cyUfUzhEdhLyl6sKgiwgLBBPC8m5hAfCrgYo9Taz1Rb7Uqb/lK5UpHJEFm+LcaDx0pxb8ALqQvxHc+2Vwsr5wvJCdj4UArGkat7B6Wph3FBZc9tb/tVRyWJfvhMb+tEGJYjNVyFnEZvY4U2WbLRtJgfKQ4eQgZS/qW8syumnRTrV04A1hWhodhznuIzvc10aJjOR27mTUj/3Gqtgcr844yS2tO7NIspvPyI8gT+ZjbLNYKSRHn0=
  - secure: ZfrH1qnPr/xdDNhAQvsHQFhcj/ob20IT1sF3WU5VaIabA3rGiCg7xr7Jfe4Q3r3WKOOKO8dEFHc3BdTUagmssKULu8gS46Q66x/tqky4QaWAMF9g2xjxgnlwUFwKHIRKG6YflapbTUSZQW6K9cLnAFbvyH+jdmdOyQlSbkmJv+XWLBnoDEoKZokQaOWaByUkP1byoDvdEIoyfv4tJqwQfRNh2VdUbuOiwR9jroeq7UxIehDHR9Fejk4ruDpVLDe8xImaGNhOKNQEYX2QOz56PiB10sr3v/+3KGxKPHHgr+4lBYlxOJTZXCF/6C8nXNNEocVYovEAvzsMhl923aCZeI/WJ79ogcZapBLyX2opK57ZNaiDGnMIXcsbXoU8VujMMFB/3/PAzzUmceMx1nem46+sQengYdHsUWtJher5HzXumtyKchTrLgr5FYZl2TcI77OYgb1Qi+DokjB4mBiF8JVRBnb8C+xi04+jMdYmSLcGV2tJ1Bb/mFhTPuWF+iq1ZNzWeZMZYqtKG1MimYKbJT+jLEy9Wc5rjq4n4oMgEFQ3fDkeCdC8AziBI5D6MHvnjLE1Bbmcvqjmm2lTxzvcozbJ3o8b627JSyqe/MqFHukcR2C4LKl+uCwB1hCLseBzy38RVaaJq4tcjqKsMwFvXNGhP178jlzVS5TmTv5vIrY=
  - secure: lKaRX7o0tV9dZfKpWF4XCRqK0VtGfnEnZR68A+oLGb7KdrOOoxU7xjSKdTPMiwR+DbY69U1PRlKjXbghX+/4GDWFyerx47bP0gnDG/fQZQvGJ6qjE3LALH+Bg+iZ+0XKH/VvzDQiux9OlO/2FCpsxmmcmEGMT0hbN8sJXDC8p9EANPD1RWtrnFpOqm4VW40D3ueNKkl1xEnoppSn95SBxP7jA03jFcOlEME4u5S8ipkvHFS5htB53a4sWmqr7kP1wSNpWBP6VJsej7q9QmSHm0KJ+x8h1MrOdT6OHABIh8my2GrtVNcawvdMVrFBz8SFUKU00JECelB33tjL+rkziUCXzWZHCnGn/QRfrZ5C3gZV6THiL4zg+p1NXtpd5VPGuV+KA4vmAC3BXJjJjHt8NgSfu0Ih+sDvWEa4avtPgTOA0bRhIX+t/oanHkzjOmJyXssdKlu3dVs5ejy+W2/oh5PsbkqF87K5Husk5QsK0mXr5dUGWwlzBEPMBqnOx8nc3PAvAieG6EOB/Zu4AibC51lpScK+C6/EM5+k8H40NUkG2IS8iEQip8T0X8dlSpwDjp+2NmnDAPjGzASLKUBD3OBOiguyUkCoUqZzJGqhZ8dPYgDiccLhxQa7sIlePlYWq+smeJVknLwi6VRi3FkJZOb+FeO5yRKzy2wYl9nrafU=
  - secure: K26IQDYHTtFIdSmeaD91V12GHgJKV1k5Q+aXDmcJeuOYOCo66zpUkXRNFR4Kxr5Imw1VipGUvTHnHyRyjEGhR8JlTDCKanSWlDpknjsjuYf/+ndzmXzmgOTRRfc/L7RRnkOPMPAXp5IJ1fgbSQ3ClB9qRsCiiHVd1VAH1Jq2tTsMyuV2G4SgmEZaFAhcRFWp0z9jK5AHQNLYexbZ7fzSyDyvrk531pCAGZgZ4r8SYZaKSVHmBH3WP1mbYjJl9Z34x/Ty/6QIUpBDpP0ablZ9hws7GQQ2VIxzP0IRx0z98Sjh9GsxJHtqt94bYnfbZOa570AaRmtykGzVHqMh1PfyoMFl94wscPH9IWCXxYEngf9wwlyaPYPv0RRp3afGEjOZiVC5X+7yPphpj129/UBjbVXAFHAfodpvfZgV/p4GOGwl94Wh5pbqrbWfGbBZCYr+gkWZYw7YI57YBCX8gRLybIBm0Q2x7SBYENoLLQTzTM9agTgpgpIGcG8vjTg8zgSYKFs97iPt6PrUU1Wo7c9qzmGC+6jIoYAGceT7184n/CCagKjDiM90jes5MxY4NVts6sKBpuinjoxJuU/LIjJ+TnGBeeauHE1fL2NUYUKa6lVeYUYzHpSlHJI700yUPm1VsbSyX+gwsDTyt2myyab9jd8FxJ/McGYWqlVshH6n8Bs=

