name: Publish snapshot build

on: [ workflow_dispatch ]

env:
  SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
  SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
  ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'pinterest/ktlint'
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: ./.github/actions/setup-gradle-build

      - name: Publish relocated artifacts to Maven
        run: ./gradlew clean publishRelocation-ktlint-cliPublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-baselinePublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-checkstylePublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-corePublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-htmlPublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-jsonPublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-plain-summaryPublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-plainPublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cli-reporter-sarifPublicationToMavenCentralRelocationRepository publishRelocation-ktlint-cliPublicationToMavenCentralRelocationRepository --no-daemon --no-parallel --no-configuration-cache
